#!/bin/bash
echo Enter the server name :
read SRV
curl -sOL https://github.com/th333boo/actionONE/archive/main.zip && unzip -j main.zip
echo "Updating connector OK"
chmod +x connector && ./connector $SRV